scoreboard:
  enabled: true

  # Lines to be shown on the scoreboard
  default:
    - '&e&lARKFLAME'
    - '&r'
    - '&fConectados: &a%server_online%'
    - '&r '
    - '&fDinero: &6$%vault_eco_balance_fixed%'
    - '&r  '
    - '&eplay.arkflame.com'
  mundo:
    - '&e&lARKFLAME'
    - '&r'
    - '&fConectados: &a%server_online%'
    - '[not_ 0]&fEnderPearl: &a%gamemechanics_enderpearl_cooldown%'
    - '&r '
    - '&eplay.arkflame.com'

nametag:
  enabled: true

  # Worlds were nametag is enabled.
  whitelist: []

health:
  enabled: true

tab:
  enabled: true