name: Scoreboard
main: dev._2lstudios.scoreboard.Main
version: 0.0.1
author: 2LS
api-version: '1.13'
commands:
  scoreboard:
    aliases:
      - sb
  nametag:
    description: "Hides or shows your nametag"
softdepend:
  - PlaceholderAPI
  - Teams